### ISSUE TITLE
How to add mouse events to Body or Fixture?

### ISSUE THREAD

**Issue by cedricdelpoux** [psychobolt/react-planck#2]
Hello, I would like update the density of a Fixture.
I can't find a way to add some event on Body, Fixture or Shape to track if the mouse is active on  an element.

I would like to achieve something like: 
```
  const [draggingShape, setDraggingShape] = useState(null)
  <Body 
    id="triangle" 
    type="dynamic" 
    onMouseDown={() => setDraggingShape("triangle")}
    onMouseUp={() => setDraggingShape(null)}
  >
        <Fixture density={draggingShape === "triangle" ? 1 : 100} onMouse>
          <Polygon
            vertices={[new Vec2(0, 0), new Vec2(0, 5), new Vec2(5, 5)]}
          />
        </Fixture>
      </Body>
```

**Comment by psychobolt** [comment]
Just adding some of my investigation:

I observed that the default testbed has bound [mouse events](https://github.com/shakiba/stage.js#mouse-and-touch):
https://github.com/psychobolt/react-planck/blob/master/src/components/Testbed/testbed.js#L282

In theory, we could add some condition inside the parent handler
```is
    // inside START event
   if (testbed.onMouseDown) {
      testbed.onMouseDown(fixture);
   }
```

and hook up the events with the modified testbed (ideally Testbed should be extensible)
```jsx
   <PlanckContainer viewProps={{
       onMouseDown: fixture => {
           if (fixture && fixture.getBody().getUserData().$$id === 'triangle') {
              setDraggingShape('triangle');
           }
       }
   }}>
   
   </PlanckContainer>
```

I'm on a holiday, but seems like a simple approach to update and include the default handling to be released. As a workaround in the meantime creating a version and passing a prop to the PlanckContainer would suffice:

```jsx
    import TestbedExtended from './TestbedExtended';

    <PlanckContainer View={TestbedExtended}  viewProps={viewProps}>
    </PlanckContainer>
```

**Comment by cedricdelpoux** [comment]
Thank you. I think it could be a very useful feature

**Comment by cedricdelpoux** [comment]
Maybe [this issue on plank.js](https://github.com/shakiba/planck.js/issues/111#issuecomment-570814222) can help

**Comment by psychobolt** [comment]
c18fa128163f19bb04b09b27347bb4530ce351eb

**Comment by psychobolt** [comment]
@cedricdelpoux Next release for this change is published on npm. Please let me know if you have any questions.

**Comment by cedricdelpoux** [comment]
Thank you very much ! I will try this

**Comment by cedricdelpoux** [comment]
I tried with `0.0.54-alpha.0` and it works, thank you!
